### PR TITLE
CMAPI2-319 Fix bugs with split logging edge cases

### PR DESCRIPTION
**Pull request by varun-akula**

### CODE REVIEW

**Comment by abhijitvk** [comment]
@varun-akula There is a sonar violation that needs to be fixed. 

Screen Shot 2019-06-05 at 8 49 17 AM

**Comment by varun-akula** [comment]
Fixed the sonar issue!

**Comment by armin-vcg** [comment]
BipBaseLogger: should be able to replace lines 177-180 with something like addToThisList.addAll(Arrays.asList(word.split(".{maxLength}|.{1,}$")));

**Comment by armin-vcg** [comment]
Rethinking the regular expression to split large strings, we may be splitting base-64 encoded strings, or even binary bytes that are being represented as a string.  To be on the safe side, it is probably best to ensure that all characters are included in the character class ("." does not include non-printable characters).  So ...
"[\u0000-\uFFFF]{"+maxLength+"}|[\u0000-\uFFFF]{1,}$"
... reads as "any unicode character between 0 and FFFF at maxLength, OR if previous spec fails then any unicode character between 0 and FFFF at length of one character or more".

**Comment by armin-vcg** [comment]
If we want to pursue optimization here, try this ...
"(?<=\\G[" + Character.MIN_CODE_POINT + "-" + Character.MAX_CODE_POINT + "{" + maxLength + "})"
... otherwise streams might present a possibility.

**Pull request merged**
